### ISSUE TITLE
Laravel 5.3

### ISSUE THREAD

**Issue by szepeviktor** [melihovv/laravel-compile-views#3]
Hello @melihovv !

Will it run on Laravel 5.3?

**Comment by szepeviktor** [comment]
It seems to be working with

```json
    "repositories" : [
        {
            "type": "git",
            "url": "https://github.com/szepeviktor/laravel-compile-views.git",
            "vendor-alias" : "melihovv"
        }
    ]
```

**Comment by melihovv** [comment]
Hello, @szepeviktor.
I tried this package only with laravel 5.5. That is why I specified 
```
"illuminate/support": "~5.5.0",
"illuminate/view": "~5.5.0"
```
constraints. I'm not sure whether it would work with the previous versions of laravel.
But I am opened for PRs.
