### ISSUE TITLE
Some Laravel views (pagination) compiled, some not (emails, errors)

### ISSUE THREAD

**Issue by trip-somers** [melihovv/laravel-compile-views#7]
I have not yet dug through the code in this project yet, but I did notice some weird behavior in what the command actually compiles.

For example, after running the command, I had compiled views for my project `/resources/views` and for some Laravel-packaged views (`/vendor/laravel/framework/src/Illuminate/Pagination/resources/views`) but not all Laravel-packaged views (`/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views`).

I am going to dig into the package a bit and see if I can turn this into a PR.

**Comment by trip-somers** [comment]
After digging, this looks like something we can tweak using the config as seen here: https://github.com/laravel/framework/blob/5.5/src/Illuminate/View/ViewServiceProvider.php#L77

I will verify that I am an idiot before closing this. :-)

**Comment by melihovv** [comment]
This package compiles all views, which are known to Laravel.

For example, 
```php
// AdminServiceProvider

// We tell Laravel that views with namespace 'admin::' should be searched inside
// __DIR__ . '/../Resources/Views' folder
$this->loadViewsFrom(__DIR__ . '/../Resources/Views', 'admin');
```
But views in this folder `/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views` are
registered dynamically, as I can see, https://github.com/laravel/framework/blob/5.5/src/Illuminate/Foundation/Exceptions/Handler.php#L398

That is why those views are not compiled.

**Comment by trip-somers** [comment]
That makes total sense since those views are designed to be overridden at the app level. Our work-around was to publish the error views into our `/resources/views` folder -- which is probably better practice anyway.

For anyone who finds this later, adding `base_path('vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/views')` to our `paths` array in `config/view.php` _*did not*_ work. (We aren't sure why exactly.)
